//Action Creators
export const GET_TOWNS = 'COMMON_GET_TOWNS';
export const GET_COLORS = 'COMMON_GET_COLORS';
export const GET_VEHICLE_TYPES = 'COMMON_GET_VEHICLE_TYPES';
export const GET_FUEL_TYPES = 'COMMON_GET_FUEL_TYPES';
export const GET_GEARBOX_TYPES = 'COMMON_GET_GEARBOX_TYPES';
export const GET_ALL_COMMONS = 'COMMON_GET_ALL_COMMONS';
export const GET_IMAGES = 'COMMON_GET_IMAGES';


//Reducers
export const UPDATE_TOWNS = 'COMMON_UPDATE_TOWNS';
export const UPDATE_COLORS = 'COMMON_UPDATE_COLORS';
export const UPDATE_VEHICLE_TYPES = 'COMMON_UPDATE_VEHICLE_TYPES';
export const UPDATE_FUEL_TYPES = 'COMMON_UPDATE_FUEL_TYPES';
export const UPDATE_GEARBOX_TYPES = 'COMMON_UPDATE_GEARBOX_TYPES';
export const UPDATE_ALL_COMMONS = 'COMMON_UPDATE_ALL_COMMONS';
export const UPDATE_IMAGES = 'COMMON_UPDATE_IMAGES';
